#!/bin/bash

prev=a
ALEART="Spoiler Alert!"
while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur != $prev ]] 
		then
			if [[ "$cur" == *"Avengers"* ]];
			then
  			      echo $ALEART
		        fi

			if [[ "$cur" != *"Avengers"* ]];
			then 
				echo $cur
			fi
			#echo $cur
			prev=$cur
		fi
	fi
done
